#!/usr/bin/env bash
# Syncs frontend/ to the S3 bucket behind CloudFront and invalidates the
# cache. CloudFormation doesn't upload arbitrary local files, so this is a
# regular post-deploy step, not something folded into `sam deploy` itself.
#
# Usage: scripts/deploy_frontend.sh [stack-name] [region]
set -euo pipefail

STACK_NAME="${1:-isto-demo}"
REGION="${2:-us-east-1}"

outputs() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

API_URL=$(outputs ApiUrl)
USER_POOL_CLIENT_ID=$(outputs UserPoolClientId)
BUCKET=$(outputs FrontendBucketName)
FRONTEND_URL=$(outputs FrontendUrl)

if [[ -z "$BUCKET" || "$BUCKET" == "None" ]]; then
  echo "Couldn't find FrontendBucketName in stack '$STACK_NAME' outputs — has it been deployed with the S3/CloudFront resources?" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONTEND_DIR="$SCRIPT_DIR/../frontend"

cat > "$FRONTEND_DIR/config.js" <<EOF
// Generated by scripts/deploy_frontend.sh for stack '$STACK_NAME' — not committed (see .gitignore).
window.ISTO_DEMO_CONFIG = {
  apiUrl: "$API_URL",
  region: "$REGION",
  userPoolClientId: "$USER_POOL_CLIENT_ID",
};
EOF

echo "Generated frontend/config.js from stack outputs."

aws s3 sync "$FRONTEND_DIR" "s3://$BUCKET/" \
  --region "$REGION" \
  --exclude "config.sample.js" \
  --delete

echo "Synced frontend/ to s3://$BUCKET/"

DIST_ID=$(aws cloudformation describe-stack-resources \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --logical-resource-id FrontendDistribution \
  --query "StackResources[0].PhysicalResourceId" \
  --output text)

aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*" --region "$REGION" > /dev/null
echo "Invalidated CloudFront cache."

echo ""
echo "Frontend URL: $FRONTEND_URL"
echo "(CloudFront can take a few minutes to fully propagate on first deploy.)"
